#!/bin/sh

######################################
# sdorfehs rc setup file
# izder456 2022 <izder456@disroot.org>
######################################

escape C-t
set ignoreresizehints 1
set barinpadding 0
set barpadding 16 14
set onlyborder 1
set bgcolor #282828
set fgcolor #ebdbb2
set barcolor #1d2021
set barborder 4
set barbordercolor #ebdbb2
set border 4
set fwcolor #ebdbb2
set bwcolor #282828
set gap 14
set padding 14 14 14 14
set barsticky 1
set bargravity nw
set font "GohuFont Nerd Font Mono"
warp 1
alias term exec st
alias tterm exec urxvt
alias scrot exec scrot -F ~/Pictures/screenshot-`date +%F`.png
alias volume-up exec pamixer -i 5
alias volume-down exec pamixer -d 5
alias volume-mute exec pamixer -t
bind space exec rofi -i -show drun -modi drun -show-icons
definekey top Print scrot
definekey top XF86AudioRaiseVolume volume-up
definekey top XF86AudioLowerVolume volume-down
definekey top XF86AudioMute volume-mute
definekey top XF86MonBrightnessUp exec xbacklight -inc 10
definekey top XF86MonBrightnessDown exec xbacklight -dec 10
bind c term
bind x exec xkill
bind Tab focuslast
bind aciitilde focus
bind f exec firefox
bind L exec betterlockscreen_rapid 6 2
bind F exec pcmanfm
bind P term -T "ncspot cli spotify client" -e ncspot
bind i term -T "htop cli system resource monitor" -e htop
bind g term -T "nvtop cli system resource monitor" -e nvtop
bind I tterm -title "neofetch cli sysfetch" -hold -e neofetch
bind N term -T "wireless network configuration" -e nmtui
bind V vmove
exec ~/.local/bin/bar.sh &
