#!/bin/sh
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && sh ~/.xprofile
[ -f ~/.Xdefaults ] && xrdb ~/.Xdefaults
exec dunst &
exec ~/.local/bin/locker &
exec picom -b &
ulimit -Sc 0
ls /usr/share/backgrounds |sort -R |tail -1 |while read file; do
    feh --bg-fill /usr/share/backgrounds/$file &
done
gentoo-pipewire-launcher &
exec sdorfehs
