#!/bin/sh
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile
[ -f ~/.Xdefaults ] && xrdb ~/.Xdefaults
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export QT_QPA_PLATFORMTHEME=gtk2
export TERM=rxvt-256color
urxvtd -q -f -o
exec dunst &
exec ~/.local/bin/locker &
exec picom -b &
ulimit -Sc 0
feh --bg-fill /usr/share/backgrounds/gyiyg.png &
exec sdorfehs
