#!/bin/sh
unset XDG_RUNTIME_DIR 
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-
export QT_QPA_PLATFORMTHEME=gtk2
export TERM=rxvt-256color 
export XDG_RUNTIME_DIR=$(mktemp -d /tmp/$(id -u)-runtime-dir.XXX)
gentoo-pipewire-launcher &
